services:
  - type: web
    name: reel-style-food-app-backend
    env: node
    buildCommand: cd Backend && npm install
    startCommand: cd Backend && npm start
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: reel-style-food-app-frontend
    env: static
    buildCommand: cd Frontend && npm install && npm run build
    staticPublishPath: ./Frontend/dist
    headers:
      - path: /index.html
        name: Cache-Control
        value: no-cache
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
